In [2]:
import pandas

In [3]:
countries_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\refugees\countries_raw.csv")

In [13]:
countries_df = pandas.DataFrame(countries_data)
countries_df

   country_code country_name          region
0           KEN        Kenya     East Africa
1           UGA      Uganda      East Africa
2           SSD  South Sudan     East Africa
3           ETH     ETHIOPIA     East Africa
4           SOM      Somalia     East Africa
5           COD     DR Congo  Central Africa
6           RWA       Rwanda     East Africa
7           BDI      Burundi     East Africa
8           TZA     Tanzania     East Africa
9           SDN        Sudan    North Africa
10          SSD  South Sudan     East Africa

In [8]:
countries_df.isnull().sum()
countries_df.describe().T

             count unique          top freq
country_code    11     10          SSD    2
country_name    11     10  South Sudan    2
region          11      3  East Africa    9

In [9]:
countries_df.duplicated().sum()

np.int64(1)

In [14]:
countries_df[countries_df.duplicated()]

   country_code country_name       region
10          SSD  South Sudan  East Africa

In [15]:
countries_df = countries_df.drop_duplicates()

In [16]:
countries_df

  country_code country_name          region
0          KEN        Kenya     East Africa
1          UGA      Uganda      East Africa
2          SSD  South Sudan     East Africa
3          ETH     ETHIOPIA     East Africa
4          SOM      Somalia     East Africa
5          COD     DR Congo  Central Africa
6          RWA       Rwanda     East Africa
7          BDI      Burundi     East Africa
8          TZA     Tanzania     East Africa
9          SDN        Sudan    North Africa

In [17]:
countries_df.to_csv (r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\refugees\countries_cleaned.csv", index=False)