In [1]:
import pandas

In [2]:
feld_offices_data = pandas.read_csv (r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\refugees\field_offices_raw.csv")

In [3]:
field_offices_df = pandas.DataFrame(feld_offices_data)
field_offices_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   office_id    15 non-null     int64
 1   office_code  15 non-null     str
 2   country      15 non-null     str
 3   city         15 non-null     str
dtypes: int64(1), str(3)
memory usage: 612.0 bytes

In [5]:
field_offices_df.isnull ().sum()

office_id      0
office_code    0
country        0
city           0
dtype: int64

In [6]:
field_offices_df.duplicated().sum()

np.int64(0)

In [7]:
field_offices_df

    office_id office_code      country         city
0           1      FO-001  South Sudan     Nairobi
1           2      FO-002        Kenya    Mogadishu
2           3      FO-003      Burundi  Addis Ababa
3           4      FO-004  South Sudan      Nairobi
4           5      FO-005     Ethiopia  Addis Ababa
5           6      FO-006        Kenya      Kampala
6           7      FO-007      Somalia         Goma
7           8      FO-008        Sudan    Mogadishu
8           9      FO-009        Sudan      Kampala
9          10      FO-010      Somalia  Addis Ababa
10         11      FO-011     DR Congo         Goma
11         12      FO-012      Somalia         Juba
12         13      FO-013      Burundi  Addis Ababa
13         14      FO-014     Tanzania         Goma
14         15      FO-015        Sudan  Addis Ababa

In [12]:
cities = {"country" : ["South Sudan","Kenya","Burundi","South Sudan","Ethiopia","Kenya","Somalia","Sudan","Sudan","Somalia","DR Congo","Somalia","Burundi","Tanzania","Sudan"],
              "city" : ["Juba","Nairobi","Bujumbura","Juba","Addis Ababa","Nairobi","Mogadishu","Khartoum","Khartoum","Mogadishu","Goma","Kismayo","Ngozi","Dodoma","Omdurman"]}
cities_df = pandas.DataFrame(cities)
cities_df

        country         city
0   South Sudan         Juba
1         Kenya      Nairobi
2       Burundi    Bujumbura
3   South Sudan         Juba
4      Ethiopia  Addis Ababa
5         Kenya      Nairobi
6       Somalia    Mogadishu
7         Sudan     Khartoum
8         Sudan     Khartoum
9       Somalia    Mogadishu
10     DR Congo         Goma
11      Somalia      Kismayo
12      Burundi        Ngozi
13     Tanzania       Dodoma
14        Sudan     Omdurman

In [14]:
field_offices_df[["country","city"]] = cities_df[["country","city"]]
field_offices_df

    office_id office_code      country         city
0           1      FO-001  South Sudan         Juba
1           2      FO-002        Kenya      Nairobi
2           3      FO-003      Burundi    Bujumbura
3           4      FO-004  South Sudan         Juba
4           5      FO-005     Ethiopia  Addis Ababa
5           6      FO-006        Kenya      Nairobi
6           7      FO-007      Somalia    Mogadishu
7           8      FO-008        Sudan     Khartoum
8           9      FO-009        Sudan     Khartoum
9          10      FO-010      Somalia    Mogadishu
10         11      FO-011     DR Congo         Goma
11         12      FO-012      Somalia      Kismayo
12         13      FO-013      Burundi        Ngozi
13         14      FO-014     Tanzania       Dodoma
14         15      FO-015        Sudan     Omdurman

In [ ]:
field