In [11]:
import pandas

In [12]:
countries_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\countries_raw.csv")

In [13]:
countries_df = pandas.DataFrame(countries_data)
countries_df

   country_code country_name          region
0           KEN        Kenya     East Africa
1           UGA      Uganda      East Africa
2           SSD  South Sudan     East Africa
3           ETH     ETHIOPIA     East Africa
4           SOM      Somalia     East Africa
5           COD     DR Congo  Central Africa
6           RWA       Rwanda     East Africa
7           BDI      Burundi     East Africa
8           TZA     Tanzania     East Africa
9           SDN        Sudan    North Africa
10          SSD  South Sudan     East Africa

In [14]:
countries_df.isnull().sum()
countries_df.describe().T

             count unique          top freq
country_code    11     10          SSD    2
country_name    11     10  South Sudan    2
region          11      3  East Africa    9

In [15]:
countries_df.duplicated().sum()

np.int64(1)

In [16]:
countries_df[countries_df.duplicated()]

   country_code country_name       region
10          SSD  South Sudan  East Africa

In [17]:
countries_df = countries_df.drop_duplicates()

In [18]:
countries_df

  country_code country_name          region
0          KEN        Kenya     East Africa
1          UGA      Uganda      East Africa
2          SSD  South Sudan     East Africa
3          ETH     ETHIOPIA     East Africa
4          SOM      Somalia     East Africa
5          COD     DR Congo  Central Africa
6          RWA       Rwanda     East Africa
7          BDI      Burundi     East Africa
8          TZA     Tanzania     East Africa
9          SDN        Sudan    North Africa

In [19]:
countries_df["country_name"].unique()

<StringArray>
[      'Kenya',    ' Uganda ', 'South Sudan',    'ETHIOPIA',     'Somalia',
    'DR Congo',      'Rwanda',     'Burundi',    'Tanzania',       'Sudan']
Length: 10, dtype: str

In [26]:
countries_df["country_name"] = countries_df["country_name"].str.title()
countries_df["country_name"] = countries_df["country_name"].str.strip()

In [27]:
countries_lookup = {"Kenya" : 1,
                    "Uganda" : 2,
                    "South Sudan" : 3,
                    "Ethiopia" : 4,
                    "Somalia" : 5,
                    "Dr Congo" : 6,
                    "Rwanda" : 7,
                    "Burundi" : 8,
                    "Tanzania" : 9,
                    "Sudan" : 10,}

In [28]:
countries_df["country_id"] = countries_df["country_name"].map(countries_lookup)

In [29]:
countries_df

  country_code country_name          region  country_id
0          KEN        Kenya     East Africa           1
1          UGA       Uganda     East Africa           2
2          SSD  South Sudan     East Africa           3
3          ETH     Ethiopia     East Africa           4
4          SOM      Somalia     East Africa           5
5          COD     Dr Congo  Central Africa           6
6          RWA       Rwanda     East Africa           7
7          BDI      Burundi     East Africa           8
8          TZA     Tanzania     East Africa           9
9          SDN        Sudan    North Africa          10

In [30]:
countries_df.to_csv (r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\countries.csv", index=False)