In [80]:
import pandas

In [81]:
ben_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\beneficiaries_raw.csv")

In [82]:
ben_df = pandas.DataFrame(ben_data)
ben_df.head()

,beneficiary_id,beneficiary_code,full_name,gender,age,country,status
0,1,BEN000001,Diamond Ramos,Female,65,Somalia,Refugee
1,2,BEN000002,Matthew Werner,Male,67,Tanzania,IDP
2,3,BEN000003,Susan Hull,Female,15,Sudan,Refugee
3,4,BEN000004,Cory Cruz,Female,12,kenya,Host Community
4,5,BEN000005,Jessica Callahan,Female,11,South Sudan,IDP

In [83]:
ben_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   beneficiary_id    5001 non-null   int64
 1   beneficiary_code  5001 non-null   str
 2   full_name         5000 non-null   str
 3   gender            5001 non-null   str
 4   age               5001 non-null   int64
 5   country           5001 non-null   str
 6   status            5001 non-null   str
dtypes: int64(2), str(5)
memory usage: 273.6 KB

In [84]:
ben_df.isnull().sum()

beneficiary_id      0
beneficiary_code    0
full_name           1
gender              0
age                 0
country             0
status              0
dtype: int64

In [85]:
ben_df = ben_df.dropna()

In [86]:
ben_df.isnull().sum()

beneficiary_id      0
beneficiary_code    0
full_name           0
gender              0
age                 0
country             0
status              0
dtype: int64

In [87]:
ben_df.describe()

       beneficiary_id          age
count      5000.00000  5000.000000
mean       2500.50200    40.023600
std        1443.51656    23.350891
min           1.00000     1.000000
25%        1250.75000    19.000000
50%        2500.50000    40.000000
75%        3750.25000    60.000000
max        5000.00000    80.000000

In [88]:
ben_df["country"].unique()

<StringArray>
[    'Somalia',    'Tanzania',       'Sudan',     ' kenya ', 'South Sudan',
    'Ethiopia',      'Rwanda',    'DR Congo',      'Uganda',     'Burundi',
       'Kenya']
Length: 11, dtype: str

In [89]:
ben_df["gender"].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [90]:
ben_df["status"].unique()

<StringArray>
['Refugee', 'IDP', 'Host Community']
Length: 3, dtype: str

In [91]:
ben_df["country"] = ben_df["country"].str.strip()
ben_df["full_name"] = ben_df["full_name"].str.strip()

In [92]:
ben_df["country"] = ben_df["country"].str.title()

In [93]:
ben_df.head()

,beneficiary_id,beneficiary_code,full_name,gender,age,country,status
0,1,BEN000001,Diamond Ramos,Female,65,Somalia,Refugee
1,2,BEN000002,Matthew Werner,Male,67,Tanzania,IDP
2,3,BEN000003,Susan Hull,Female,15,Sudan,Refugee
3,4,BEN000004,Cory Cruz,Female,12,Kenya,Host Community
4,5,BEN000005,Jessica Callahan,Female,11,South Sudan,IDP

In [94]:
ben_df.describe().T

,count,mean,std,min,25%,50%,75%,max
beneficiary_id,5000.0,2500.5020,1443.516560,1.0,1250.75,2500.5,3750.25,5000.0
age,5000.0,40.0236,23.350891,1.0,19.00,40.0,60.00,80.0

In [95]:
ben_df.duplicated().sum()

np.int64(1)

In [96]:
ben_df = ben_df.drop_duplicates()

In [97]:
ben_df.head()

,beneficiary_id,beneficiary_code,full_name,gender,age,country,status
0,1,BEN000001,Diamond Ramos,Female,65,Somalia,Refugee
1,2,BEN000002,Matthew Werner,Male,67,Tanzania,IDP
2,3,BEN000003,Susan Hull,Female,15,Sudan,Refugee
3,4,BEN000004,Cory Cruz,Female,12,Kenya,Host Community
4,5,BEN000005,Jessica Callahan,Female,11,South Sudan,IDP

In [98]:
ben_df.rename(columns={"country": "country_id"}, inplace=True)

In [99]:
ben_df

,beneficiary_id,beneficiary_code,full_name,gender,age,country_id,status
0,1,BEN000001,Diamond Ramos,Female,65,Somalia,Refugee
1,2,BEN000002,Matthew Werner,Male,67,Tanzania,IDP
2,3,BEN000003,Susan Hull,Female,15,Sudan,Refugee
3,4,BEN000004,Cory Cruz,Female,12,Kenya,Host Community
4,5,BEN000005,Jessica Callahan,Female,11,South Sudan,IDP
...,...,...,...,...,...,...,...
4995,4996,BEN004996,Jeff Williams,Male,38,Tanzania,Refugee
4996,4997,BEN004997,Donald Johnston,Female,63,Tanzania,IDP
4997,4998,BEN004998,Kimberly Moreno,Male,78,Burundi,Host Community
4998,4999,BEN004999,Robin Miller,Male,70,Dr Congo,Host Community
4999,5000,BEN005000,Michelle Gonzales,Male,38,Tanzania,IDP

In [100]:
countries_lookup = {"Kenya" : 1,
                    "Uganda" : 2,
                    "South Sudan" : 3,
                    "Ethiopia" : 4,
                    "Somalia" : 5,
                    "Dr Congo" : 6,
                    "Rwanda" : 7,
                    "Burundi" : 8,
                    "Tanzania" : 9,
                    "Sudan" : 10,}

In [101]:
ben_df["country_id"] = ben_df["country_id"].map(countries_lookup)

In [102]:
ben_df.head()

,beneficiary_id,beneficiary_code,full_name,gender,age,country_id,status
0,1,BEN000001,Diamond Ramos,Female,65,5,Refugee
1,2,BEN000002,Matthew Werner,Male,67,9,IDP
2,3,BEN000003,Susan Hull,Female,15,10,Refugee
3,4,BEN000004,Cory Cruz,Female,12,1,Host Community
4,5,BEN000005,Jessica Callahan,Female,11,3,IDP

In [103]:
ben_df.to_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\beneficiaries.csv",index=False)