In [6]:
import pandas

In [7]:
food_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\food_distribution_raw.csv")
food_df = pandas.DataFrame(food_data)
food_df.head(10)

,distribution_id,project_id,beneficiary_id,food_item,quantity,unit,country,distribution_date,warehouse_code
0,1,15,2455,Rice,68,kg,Uganda,2026-01-31,WH-004
1,2,22,4396,Beans,68,kg,Ethiopia,2026-03-02,WH-002
2,3,20,3119,Salt,73,kg,Somalia,2025-02-04,WH-002
3,4,10,4061,Beans,92,kg,Ethiopia,2024-10-13,WH-004
4,5,25,826,Sugar,-20,kg,South Sudan,2025-01-29,WH-003
5,6,21,112,Maize Flour,54,kg,Ethiopia,2025-05-09,WH-004
6,7,19,3581,Sugar,12,kg,Uganda,2025-12-20,WH-004
7,8,29,790,Sugar,82,kg,Somalia,2025-09-22,WH-001
8,9,28,3641,Maize Flour,33,kg,kenya,2025-02-22,WH-001
9,10,20,3604,Maize Flour,7,kg,Uganda,2025-12-03,WH-001

In [8]:
food_df.isnull().sum()

distribution_id      0
project_id           0
beneficiary_id       0
food_item            1
quantity             0
unit                 0
country              0
distribution_date    0
warehouse_code       0
dtype: int64

In [9]:
food_df = food_df.dropna()

In [10]:
food_df[food_df.duplicated()]

,distribution_id,project_id,beneficiary_id,food_item,quantity,unit,country,distribution_date,warehouse_code
5000,26,19,4813,Cooking Oil,25,kg,Uganda,2026-04-07,WH-002

In [11]:
food_df = food_df.drop_duplicates()

In [12]:
food_df.info()

<class 'pandas.DataFrame'>
Index: 4999 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   distribution_id    4999 non-null   int64
 1   project_id         4999 non-null   int64
 2   beneficiary_id     4999 non-null   int64
 3   food_item          4999 non-null   str
 4   quantity           4999 non-null   int64
 5   unit               4999 non-null   str
 6   country            4999 non-null   str
 7   distribution_date  4999 non-null   str
 8   warehouse_code     4999 non-null   str
dtypes: int64(4), str(5)
memory usage: 390.5 KB

In [13]:
food_df["distribution_date"] = pandas.to_datetime(food_df["distribution_date"],format='mixed', errors='coerce')

In [14]:
food_df["distribution_date"].isnull().sum()

np.int64(0)

In [15]:
food_df["food_item"].unique()

<StringArray>
['Rice', 'Beans', 'Salt', 'Sugar', 'Maize Flour', 'Cooking Oil', 'Lentils']
Length: 7, dtype: str

In [16]:
food_df["country"].unique()

<StringArray>
['Uganda', 'Ethiopia', 'Somalia', 'South Sudan', ' kenya ', 'Kenya']
Length: 6, dtype: str

In [17]:
food_df["country"] =food_df["country"].str.strip()

In [18]:
food_df["country"] =food_df["country"].str.title()

In [ ]:
food_df.describe().T

In [24]:
food_df["quantity"] = food_df["quantity"].abs()
food_df.head(10)

,distribution_id,project_id,beneficiary_id,food_item,quantity,unit,country,distribution_date,warehouse_code
0,1,15,2455,Rice,68,kg,Uganda,2026-01-31,WH-004
1,2,22,4396,Beans,68,kg,Ethiopia,2026-03-02,WH-002
2,3,20,3119,Salt,73,kg,Somalia,2025-02-04,WH-002
3,4,10,4061,Beans,92,kg,Ethiopia,2024-10-13,WH-004
4,5,25,826,Sugar,20,kg,South Sudan,2025-01-29,WH-003
5,6,21,112,Maize Flour,54,kg,Ethiopia,2025-05-09,WH-004
6,7,19,3581,Sugar,12,kg,Uganda,2025-12-20,WH-004
7,8,29,790,Sugar,82,kg,Somalia,2025-09-22,WH-001
8,9,28,3641,Maize Flour,33,kg,Kenya,2025-02-22,WH-001
9,10,20,3604,Maize Flour,7,kg,Uganda,2025-12-03,WH-001

In [23]:
food_df.to_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\food_distribution.csv", index=False)