In [23]:
import pandas

In [24]:
food_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\food_distribution_raw.csv")
food_df = pandas.DataFrame(food_data)
food_df.head(10)

,distribution_id,project_id,beneficiary_id,food_item,quantity,unit,country,distribution_date,warehouse_code
0,1,15,2455,Rice,68,kg,Uganda,2026-01-31,WH-004
1,2,22,4396,Beans,68,kg,Ethiopia,2026-03-02,WH-002
2,3,20,3119,Salt,73,kg,Somalia,2025-02-04,WH-002
3,4,10,4061,Beans,92,kg,Ethiopia,2024-10-13,WH-004
4,5,25,826,Sugar,-20,kg,South Sudan,2025-01-29,WH-003
5,6,21,112,Maize Flour,54,kg,Ethiopia,2025-05-09,WH-004
6,7,19,3581,Sugar,12,kg,Uganda,2025-12-20,WH-004
7,8,29,790,Sugar,82,kg,Somalia,2025-09-22,WH-001
8,9,28,3641,Maize Flour,33,kg,kenya,2025-02-22,WH-001
9,10,20,3604,Maize Flour,7,kg,Uganda,2025-12-03,WH-001

In [25]:
food_df.isnull().sum()

distribution_id      0
project_id           0
beneficiary_id       0
food_item            1
quantity             0
unit                 0
country              0
distribution_date    0
warehouse_code       0
dtype: int64

In [26]:
food_df = food_df.dropna()

In [27]:
food_df[food_df.duplicated()]

,distribution_id,project_id,beneficiary_id,food_item,quantity,unit,country,distribution_date,warehouse_code
5000,26,19,4813,Cooking Oil,25,kg,Uganda,2026-04-07,WH-002

In [28]:
food_df = food_df.drop_duplicates()

In [29]:
food_df.info()

<class 'pandas.DataFrame'>
Index: 4999 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   distribution_id    4999 non-null   int64
 1   project_id         4999 non-null   int64
 2   beneficiary_id     4999 non-null   int64
 3   food_item          4999 non-null   str
 4   quantity           4999 non-null   int64
 5   unit               4999 non-null   str
 6   country            4999 non-null   str
 7   distribution_date  4999 non-null   str
 8   warehouse_code     4999 non-null   str
dtypes: int64(4), str(5)
memory usage: 390.5 KB

In [30]:
food_df["distribution_date"] = pandas.to_datetime(food_df["distribution_date"],format='mixed', errors='coerce')

In [31]:
food_df["distribution_date"].isnull().sum()

np.int64(0)

In [32]:
food_df["food_item"].unique()

<StringArray>
['Rice', 'Beans', 'Salt', 'Sugar', 'Maize Flour', 'Cooking Oil', 'Lentils']
Length: 7, dtype: str

In [33]:
food_df["country"].unique()

<StringArray>
['Uganda', 'Ethiopia', 'Somalia', 'South Sudan', ' kenya ', 'Kenya']
Length: 6, dtype: str

In [34]:
food_df["country"] =food_df["country"].str.strip()

In [35]:
food_df["country"] =food_df["country"].str.title()

In [36]:
food_df.describe().T

,count,mean,min,25%,50%,75%,max,std
distribution_id,4999.0,2500.996399,1.0,1251.5,2501.0,3750.5,5000.0,1443.237544
project_id,4999.0,15.541508,1.0,8.0,15.0,23.0,30.0,8.733633
beneficiary_id,4999.0,2532.592118,1.0,1291.5,2510.0,3812.0,5000.0,1449.444702
quantity,4999.0,50.29766,-20.0,25.0,51.0,75.0,100.0,28.825589
distribution_date,4999,2025-07-23 20:32:53.194639,2024-07-19 00:00:00,2025-01-22 00:00:00,2025-07-28 00:00:00,2026-01-18 00:00:00,2026-07-19 00:00:00,NaN

In [37]:
food_df["quantity"] = food_df["quantity"].abs()
food_df.head(10)

,distribution_id,project_id,beneficiary_id,food_item,quantity,unit,country,distribution_date,warehouse_code
0,1,15,2455,Rice,68,kg,Uganda,2026-01-31,WH-004
1,2,22,4396,Beans,68,kg,Ethiopia,2026-03-02,WH-002
2,3,20,3119,Salt,73,kg,Somalia,2025-02-04,WH-002
3,4,10,4061,Beans,92,kg,Ethiopia,2024-10-13,WH-004
4,5,25,826,Sugar,20,kg,South Sudan,2025-01-29,WH-003
5,6,21,112,Maize Flour,54,kg,Ethiopia,2025-05-09,WH-004
6,7,19,3581,Sugar,12,kg,Uganda,2025-12-20,WH-004
7,8,29,790,Sugar,82,kg,Somalia,2025-09-22,WH-001
8,9,28,3641,Maize Flour,33,kg,Kenya,2025-02-22,WH-001
9,10,20,3604,Maize Flour,7,kg,Uganda,2025-12-03,WH-001

In [38]:
food_df =  food_df.rename(columns={"country":"country_id"})

In [39]:
countries_lookup = {"Kenya" : 1,
                    "Uganda" : 2,
                    "South Sudan" : 3,
                    "Ethiopia" : 4,
                    "Somalia" : 5,
                    "Dr Congo" : 6,
                    "Rwanda" : 7,
                    "Burundi" : 8,
                    "Tanzania" : 9,
                    "Sudan" : 10,}

In [40]:
food_df["country_id"] = food_df["country_id"].map(countries_lookup)

In [41]:
food_df.head()

,distribution_id,project_id,beneficiary_id,food_item,quantity,unit,country_id,distribution_date,warehouse_code
0,1,15,2455,Rice,68,kg,2,2026-01-31,WH-004
1,2,22,4396,Beans,68,kg,4,2026-03-02,WH-002
2,3,20,3119,Salt,73,kg,5,2025-02-04,WH-002
3,4,10,4061,Beans,92,kg,4,2024-10-13,WH-004
4,5,25,826,Sugar,20,kg,3,2025-01-29,WH-003

In [42]:
food_df.to_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\food_distribution.csv", index=False)