In [2]:
import pandas

In [4]:
health_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\health_services_raw.csv")
health_df = pandas.DataFrame(health_data)
health_df.head()

,service_id,beneficiary_id,facility_code,service_type,country,service_date,outcome
0,1,1393,HF-012,General Consultation,South Sudan,2026-05-22,Referred
1,2,3920,HF-006,Nutrition Screening,Ethiopia,2025-03-27,Recovered
2,3,2875,HF-014,General Consultation,South Sudan,2026-07-18,Recovered
3,4,2895,HF-019,General Consultation,Ethiopia,2026-04-21,Referred
4,5,4165,HF-003,Mental Health,Uganda,2025-12-24,Follow-up

In [7]:
health_df["service_date"] = pandas.to_datetime(health_df["service_date"],format='mixed',errors='coerce')

In [9]:
health_df = health_df.dropna()

In [11]:
health_df.info()

<class 'pandas.DataFrame'>
Index: 5000 entries, 0 to 5000
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_id      5000 non-null   int64
 1   beneficiary_id  5000 non-null   int64
 2   facility_code   5000 non-null   str
 3   service_type    5000 non-null   str
 4   country         5000 non-null   str
 5   service_date    5000 non-null   datetime64[us]
 6   outcome         5000 non-null   str
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 312.5 KB

In [13]:
health_df.duplicated().sum()
health_df = health_df.drop_duplicates()

In [16]:
health_df["service_type"].unique()

<StringArray>
['General Consultation',  'Nutrition Screening',        'Mental Health',
        'Maternal Care',          'Vaccination']
Length: 5, dtype: str

In [17]:
health_df["outcome"].unique()

<StringArray>
['Referred', 'Recovered', 'Follow-up']
Length: 3, dtype: str

In [28]:
health_df["country"].unique()

<StringArray>
['South Sudan', 'Ethiopia', 'Uganda', 'Kenya', 'Somalia']
Length: 5, dtype: str

In [26]:
health_df["country"] = health_df["country"].str.strip()

In [27]:
health_df["country"] = health_df["country"].str.title()

In [18]:
health_df.describe().T

,count,mean,min,25%,50%,75%,max,std
service_id,4999.0,2500.9984,1.0,1251.5,2501.0,3750.5,5000.0,1443.234096
beneficiary_id,4999.0,2487.284857,1.0,1246.0,2510.0,3736.0,5000.0,1439.999064
service_date,4999,2025-07-17 22:17:44.372874,2024-03-11 00:00:00,2025-01-22 00:00:00,2025-07-14 00:00:00,2026-01-13 12:00:00,2026-07-19 00:00:00,NaN

In [19]:
health_df.head()

,service_id,beneficiary_id,facility_code,service_type,country,service_date,outcome
0,1,1393,HF-012,General Consultation,South Sudan,2026-05-22,Referred
1,2,3920,HF-006,Nutrition Screening,Ethiopia,2025-03-27,Recovered
2,3,2875,HF-014,General Consultation,South Sudan,2026-07-18,Recovered
3,4,2895,HF-019,General Consultation,Ethiopia,2026-04-21,Referred
4,5,4165,HF-003,Mental Health,Uganda,2025-12-24,Follow-up

In [31]:
health_df.to_csv( r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\health_services.csv", index=False)