In [24]:
import pandas

In [25]:
cash_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\cash_assistance_raw.csv")
cash_df = pandas.DataFrame(cash_data)
cash_df.head()

,cash_assistance_id,beneficiary_id,project_id,country,amount,currency,payment_method,payment_date
0,1,1897,30,Uganda,175.71,USD,Mobile Money,2026-03-05
1,2,3461,15,Somalia,65.70,USD,Bank Transfer,2025-10-09
2,3,1638,27,Kenya,158.84,USD,Voucher,2026-02-13
3,4,3081,6,Somalia,247.85,USD,Voucher,2024-09-09
4,5,2042,23,Ethiopia,320.22,USD,Bank Transfer,2025-05-30

In [26]:
cash_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4001 entries, 0 to 4000
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cash_assistance_id  4001 non-null   int64
 1   beneficiary_id      4001 non-null   int64
 2   project_id          4001 non-null   int64
 3   country             4001 non-null   str
 4   amount              4001 non-null   float64
 5   currency            4001 non-null   str
 6   payment_method      4000 non-null   str
 7   payment_date        4001 non-null   str
dtypes: float64(1), int64(3), str(4)
memory usage: 250.2 KB

In [27]:
cash_df = cash_df.dropna()

In [28]:
cash_df["payment_date"] = pandas.to_datetime(cash_df["payment_date"], format='mixed', errors='coerce')

In [29]:
cash_df.head()

,cash_assistance_id,beneficiary_id,project_id,country,amount,currency,payment_method,payment_date
0,1,1897,30,Uganda,175.71,USD,Mobile Money,2026-03-05
1,2,3461,15,Somalia,65.70,USD,Bank Transfer,2025-10-09
2,3,1638,27,Kenya,158.84,USD,Voucher,2026-02-13
3,4,3081,6,Somalia,247.85,USD,Voucher,2024-09-09
4,5,2042,23,Ethiopia,320.22,USD,Bank Transfer,2025-05-30

In [30]:
cash_df["country"].unique()

<StringArray>
['Uganda', 'Somalia', 'Kenya', 'Ethiopia', 'South Sudan', ' kenya ']
Length: 6, dtype: str

In [31]:
cash_df["country"] = cash_df["country"].str.strip()

In [32]:
cash_df["country"] = cash_df["country"].str.title()

In [33]:
cash_df["currency"].unique()

<StringArray>
['USD']
Length: 1, dtype: str

In [34]:
cash_df["payment_method"].unique()

<StringArray>
['Mobile Money', 'Bank Transfer', 'Voucher', 'Cash']
Length: 4, dtype: str

In [35]:
cash_df.duplicated().sum()

np.int64(1)

In [36]:
cash_df = cash_df.drop_duplicates()

In [37]:
cash_df.describe().T

,count,mean,min,25%,50%,75%,max,std
cash_assistance_id,3999.0,2000.996249,1.0,1001.5,2001.0,3000.5,4000.0,1154.562667
beneficiary_id,3999.0,2510.671418,2.0,1302.0,2511.0,3758.5,5000.0,1437.85455
project_id,3999.0,15.514629,1.0,8.0,15.0,23.0,30.0,8.626641
amount,3999.0,262.517472,-100.0,140.835,264.85,384.545,499.62,138.765817
payment_date,3999,2025-07-22 14:53:23.000750,2024-07-19 00:00:00,2025-01-24 00:00:00,2025-07-20 00:00:00,2026-01-20 00:00:00,2026-07-19 00:00:00,NaN

In [38]:
cash_df["amount"] = cash_df["amount"].abs()

In [39]:
cash_df.rename(columns={"country":"country_id"}, inplace=True)

In [40]:
countries_lookup = {"Kenya" : 1,
                    "Uganda" : 2,
                    "South Sudan" : 3,
                    "Ethiopia" : 4,
                    "Somalia" : 5,
                    "Dr Congo" : 6,
                    "Rwanda" : 7,
                    "Burundi" : 8,
                    "Tanzania" : 9,
                    "Sudan" : 10,}

In [41]:
cash_df["country_id"] = cash_df["country_id"].map(countries_lookup)

In [42]:
cash_df.head()

,cash_assistance_id,beneficiary_id,project_id,country_id,amount,currency,payment_method,payment_date
0,1,1897,30,2,175.71,USD,Mobile Money,2026-03-05
1,2,3461,15,5,65.70,USD,Bank Transfer,2025-10-09
2,3,1638,27,1,158.84,USD,Voucher,2026-02-13
3,4,3081,6,5,247.85,USD,Voucher,2024-09-09
4,5,2042,23,4,320.22,USD,Bank Transfer,2025-05-30

In [43]:
cash_df.to_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\cash_assistance.csv", index=False)