In [29]:
import pandas

In [30]:
funding_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\funding_raw.csv")
funding_df = pandas.DataFrame(funding_data)
funding_df.head()

,funding_id,project_id,donor_id,approved_budget,amount_spent,remaining_budget,currency,fiscal_year
0,1,11,3,173810.25,108911.73,64898.52,USD,2025
1,2,27,1,100439.65,42657.45,57782.20,EUR,2024
2,3,2,4,360332.43,64151.59,296180.84,USD,2024
3,4,13,6,232611.46,37335.53,195275.93,EUR,2024
4,5,4,8,NaN,225285.99,197244.07,USD,2025

In [31]:
funding_df.describe().T

,count,mean,std,min,25%,50%,75%,max
funding_id,800.0,400.500000,231.084400,1.00,200.7500,400.500,600.2500,800.00
project_id,800.0,15.560000,8.675135,1.00,8.0000,15.000,23.0000,30.00
donor_id,800.0,4.445000,2.280016,1.00,2.0000,4.000,6.0000,8.00
approved_budget,799.0,247468.969186,139032.166040,5470.53,132045.5100,248019.320,356823.7600,499835.31
amount_spent,800.0,124075.269662,106386.124526,-500.00,38016.0400,95167.235,189024.0550,487311.51
remaining_budget,800.0,123610.913300,107091.760190,89.10,38633.4275,93373.195,184941.1475,483903.71
fiscal_year,800.0,2024.011250,0.808976,2023.00,2023.0000,2024.000,2025.0000,2025.00

In [32]:
funding_df.head()

,funding_id,project_id,donor_id,approved_budget,amount_spent,remaining_budget,currency,fiscal_year
0,1,11,3,173810.25,108911.73,64898.52,USD,2025
1,2,27,1,100439.65,42657.45,57782.20,EUR,2024
2,3,2,4,360332.43,64151.59,296180.84,USD,2024
3,4,13,6,232611.46,37335.53,195275.93,EUR,2024
4,5,4,8,NaN,225285.99,197244.07,USD,2025

In [33]:
funding_df[funding_df["amount_spent"] < 0]

,funding_id,project_id,donor_id,approved_budget,amount_spent,remaining_budget,currency,fiscal_year
9,10,19,6,211580.13,-500.0,210790.06,USD,2024

In [34]:
funding_df["amount_spent"] = funding_df["approved_budget"] - funding_df["remaining_budget"]

In [35]:
funding_df.isnull().sum()

funding_id          0
project_id          0
donor_id            0
approved_budget     1
amount_spent        1
remaining_budget    0
currency            0
fiscal_year         0
dtype: int64

In [36]:
funding_df = funding_df.dropna()

In [37]:
funding_df.info()

<class 'pandas.DataFrame'>
Index: 799 entries, 0 to 799
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   funding_id        799 non-null    int64
 1   project_id        799 non-null    int64
 2   donor_id          799 non-null    int64
 3   approved_budget   799 non-null    float64
 4   amount_spent      799 non-null    float64
 5   remaining_budget  799 non-null    float64
 6   currency          799 non-null    str
 7   fiscal_year       799 non-null    int64
dtypes: float64(3), int64(4), str(1)
memory usage: 56.2 KB

In [38]:
funding_df.duplicated().sum()

np.int64(0)

In [39]:
funding_df["currency"].unique()

<StringArray>
['USD', 'EUR', 'usd ']
Length: 3, dtype: str

In [40]:
funding_df["currency"] = funding_df["currency"].str.upper()

In [41]:
funding_df["currency"] = funding_df["currency"].str.strip()

In [42]:
funding_df.to_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\funding.csv")